version: "3.9"

services:
  server:
    build:
      context: ./
      dockerfile: src/server/CoursePlatform.Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
      - keycloak
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=CoursePlatform;User Id=sa;Password=Your_password123;

  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    ports:
      - "4200:80"   
    depends_on:
      - server

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: courseplatform-db
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
    ports:
      - "8080:8080"
