name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set version
      run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./src/server
        file: ./src/server/CoursePlatform.Api/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/course-platform-server:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/course-platform-server:${{ env.VERSION }}
