name: Docker Build & Push

on:
  workflow_call:
    secrets: inherit
    inputs:
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      image:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug secrets
        run: |
          echo "Docker username length: ${#DOCKERHUB_USERNAME}"
          
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version
        run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image }}:${{ env.VERSION }}

